#Ejercicio: Análisis de Datos de Empleados

**Enunciado**

Eres el analista de recursos humanos de una empresa que ha registrado la información de
sus empleados en un archivo CSV. La empresa te ha proporcionado un archivo CSV con la
siguiente información:
- employee_id: El identificador del empleado.
- name: El nombre del empleado.
- department: El departamento en el que trabaja el empleado.
- position: El cargo del empleado.
- salary: El salario mensual del empleado.
- date_of_hire: La fecha de contratación del empleado.

Tu tarea es analizar estos datos para responder las siguientes preguntas:
1. ¿Cuál es el salario promedio por departamento?
2. ¿Cuál es el número total de empleados por departamento?
3. ¿Cuáles son los 5 empleados con los salarios más altos?
4. ¿Cuál es el salario promedio de los empleados contratados en los últimos 5 años?
5. ¿Cuáles son los 3 departamentos con los salarios promedios más bajos?

In [1]:
import pandas as pd

In [53]:
empleados = pd.read_csv("employees_data.csv", thousands='.')
salario_medio_departamento = empleados.groupby(by='department')['salary'].mean()
salario_medio_departamento

department
Engineering    1.349873e+16
Finance        1.471012e+16
HR             1.655198e+16
Marketing      9.898509e+15
Sales          1.047392e+16
Name: salary, dtype: float64

In [31]:
empleados.groupby(by='department')['employee_id'].count()

department
Engineering    16
Finance        19
HR             23
Marketing      20
Sales          22
Name: employee_id, dtype: int64

In [37]:
empleados.sort_values('salary', ascending=False).head()

,employee_id,name,department,position,salary,date_of_hire
9,10,Employee 10,Finance,Developer,64509736694319900,2019-11-19 12:33:23.818334
65,66,Employee 66,HR,Coordinator,63185265359486700,2017-07-24 12:33:23.819718
78,79,Employee 79,HR,Manager,56652617776993000,2020-08-17 12:33:23.819718
85,86,Employee 86,HR,Salesperson,53885054184550000,2016-05-21 12:33:23.819718
59,60,Employee 60,Finance,Analyst,51998303280144200,2015-12-24 12:33:23.819718

In [51]:
empleados['date_of_hire'] = pd.to_datetime(empleados['date_of_hire'])
empleados_ultimos_5_anios = empleados[empleados['date_of_hire'] >= pd.Timestamp.now() - pd.DateOffset(years=5)]
empleados_ultimos_5_anios['salary'].mean()

1.0086384391998964e+16

In [62]:
salario_medio_departamento.sort_values().head(3)

department
Marketing      9.898509e+15
Sales          1.047392e+16
Engineering    1.349873e+16
Name: salary, dtype: float64