##10ED02_ 02_Funciones
###Ejercicio Dirigido: Aplicación de Funciones en Pandas
Enunciado:

En este ejercicio, aplicarás diversas funciones a un DataFrame utilizando Pandas. El objetivo es
transformar y analizar los datos en el DataFrame df, que contiene información sobre productos y sus
ventas.


1. Crea un DataFrame llamado df con los siguientes datos:
Product Price Quantity Category
- A 10 50 Food
- B 20 30 Beverage
- C 15 40 Food
- D 25 20 Beverage
- E 30 10 Food

In [61]:
import pandas as pd

data = {'Product': ['A', 'B', 'C', 'D', 'E'],
        'Price': [10, 20, 15, 25, 30],
        'Quantity': [50, 30, 40, 20, 10],
        'Category': ['Food', 'Beverage', 'Food', 'Beverage', 'Food']}
df = pd.DataFrame(data)


2. Define una función llamada discount que aplique un descuento del 10% a los precios de los
productos.

In [62]:
def discount(quantity: int): df['Price'] = df['Price'] * (1-quantity/100)


3. Aplica la función discount a la columna Price del DataFrame df y muestra los resultados.

In [63]:
discount(10)
df.head()

  Product  Price  Quantity  Category
0       A    9.0        50      Food
1       B   18.0        30  Beverage
2       C   13.5        40      Food
3       D   22.5        20  Beverage
4       E   27.0        10      Food


4. Define una función llamada total_sales que calcule el total de ventas (Price * Quantity) para cada
producto.

In [64]:
def total_sales(): return df['Price'] * df['Quantity']


5. Utiliza la función total_sales para calcular el total de ventas y añade una nueva columna Total
Sales al DataFrame df.

In [65]:
df['Total Sales'] = total_sales()


6. Aplica una función lambda a la columna Category para clasificar los productos como 'High' si el
Price es mayor a 20, y 'Low' en caso contrario. Añade esta clasificación en una nueva columna
llamada Price Category.

In [66]:
df['Price Category'] = df['Price'].apply(lambda x: 'High' if x > 20 else 'Low')


7. Utiliza la función map y una expresión lambda para convertir los nombres de los productos en
mayúsculas y actualizar la columna Product.

In [67]:
df['Product'] = df['Product'].map(lambda x: x.upper())


8. Filtra el DataFrame para mostrar solo los productos que pertenecen a la categoría 'Food' y tienen
un Price mayor a 15.

In [74]:
df.query("Category == 'Food' and Price > 15")

  Product  Price  Quantity Category  Total Sales Price Category
4       E   27.0        10     Food        270.0           High